# Makefile for Lab03-Blinky, ELEC424 Fall 2014
# Authors: Jie Liao, Abeer Javed, Steven Arroyo. Rice University 
# Derived from the crazyflie-firmware Makefile

# Path Definitions
STM_LIB ?= ??

# Compiler 
CC = arm-none-eabi-gcc

# Particular processor
PROCESSOR = -mcpu=cortex-m3 -mthumb

# Directories of used header files
INCLUDE = ??

# STM chip specific flags
STFLAGS = -DSTM32F10X_MD -include $(??)/stm32f10x_conf.h

# Define the compiler flags
CFLAGS = -O0 -g3 $(PROCESSOR) $(INCLUDE) $(STFLAGS) -Wl,--gc-sections -T $(??)/stm32_flash.ld

# Build all relevant files and create .elf
all:
	@$(CC) $(CFLAGS) $(??)/startup_stm32f10x_md.s ??

# Program .elf into Crazyflie flash memory via the busblaster
flash:
	@openocd -d0 -f interface/busblaster.cfg -f target/stm32f1x.cfg -c init -c targets -c "reset halt" -c "flash write_image erase blinky_fast.elf" -c "verify_image blinky_fast.elf" -c "reset run" -c shutdown
	??

# Runs OpenOCD, opens GDB terminal, and establishes connection with Crazyflie
debug:
	??
	@xterm -iconic -e openocd -f interface/busblaster.cfg -f target/stm32f1x.cfg -c 'init; targets; reset halt;' &
	@arm-none-eabi-gdb -ex 'target remote localhost:3333' blinky_fast.elf
	@killall openocd

# Remove all files generated by target 'all'
clean:
	??
