# Makefile for Lab03-Blinky, ELEC424 Fall 2014
# Authors: Jie Liao, Abeer Javed, Steven Arroyo. Rice University 
# Derived from the crazyflie-firmware Makefile

# Path Definitions
STM_LIB = ??
??

# Compiler 
CC = arm-none-eabi-gcc

# Particular processor
PROCESSOR = -mcpu=cortex-m3 -mthumb

# Directories of used header files
INCLUDE = ??

# STM chip specific flags
STFLAGS = -DSTM32F10X_MD -include $(??)/stm32f10x_conf.h

# Define the compiler flags
CFLAGS = -O0 -g3 $(PROCESSOR) $(INCLUDE) $(STFLAGS) -Wl,--gc-sections -T $(??)/stm32_flash.ld

# Build all relevant files and create .elf
all:
	@$(CC) $(CFLAGS) $(??)/startup_stm32f10x_md.s ??

# Program .elf into Crazyflie flash memory via the busblaster
flash:
	??

# Runs OpenOCD, opens GDB terminal, and establishes connection with Crazyflie
debug:
	??

# Remove all files generated by target 'all'
clean:
	??
